VentPuzzleSetup
KOMPOT-IZ-FIKUSA/Fugam- pull request #12
Opened 2024-10-10 16:03 UTC by Chpcunningham

About 6 Commits:
- Setting up the selected itemSlot logic to the vent
- making sure vent only opens if screwdriver is selected
- added hint message if no item is selected and attempts to open vent
- added extra table, one is taller and we can push the small one to jump up(Change these assets later)

2024-10-13 02:36 UTC, KOMPOT-IZ-FIKUSA commented on Assets/CoreSystems/Storage/Scripts/PlayerInventory.cs
A bad decesion to make it public. If you really need to get the key from an external script, use a getter with a private field. Hovewer, I believe that you don't want to get that key from any other place.

2024-10-13 02:47 UTC, KOMPOT-IZ-FIKUSA requested changes
Problems:
1) public property instead of private for no reason
2) unclear reference to screwdiver from screwdriver
3) adding an unused field and not initialising

2024-10-13 02:47 UTC, KOMPOT-IZ-FIKUSA commented on Assets/CoreSystems/Storage/Scripts/PlayerInventory.cs
A bad decesion to make it public. If you really need to get the key from an external script, use a getter with a private field. Hovewer, I believe that you don't want to get that key from any other place.

2024-10-13 02:47 UTC, KOMPOT-IZ-FIKUSA commented on Assets/GameplayObjects/Screwdriver/InteractableScrewdriver.cs
I do not understand the purpose of creating a private field referring to the screwdriver.
If screwdiriver refers to the current object, just use the "gameObject" field from MonoBehaviour: 
Destroy(gameObject);
If it refers to any other object, if it is a parent, you can use transform.parent.
Since it is unclear what this object refers to, it is a good idea to put some comments in case if it actually refers to some other objects

2024-10-13 02:47 UTC, KOMPOT-IZ-FIKUSA commented on Assets/Scripts/InteractableVent.cs
A redundant field referencing PlayerInventory that is not initialised. I hope I can see it initialised in a future commit.

2024-10-13 02:49 UTC, KOMPOT-IZ-FIKUSA commented on Assets/CoreSystems/Storage/Scripts/PlayerInventory.cs
The problem is fixed in the next commit.

2024-10-13 03:11 UTC, KOMPOT-IZ-FIKUSA requested changes
1) Remove the name from SlotItem, just use the existing one in SpriteItem
2) Don't get InteractableObject from scene and SlotItem from it, use string comparison instead.

2024-10-13 03:11 UTC, Aleksei-Spiridonov commented on Assets/CoreSystems/Storage/Scripts/BaseStorageSystem/SlotItem.cs
Item name already exists as a field in SpriteItem. There is no need to change the higher abstraction level to have a name.
I might agree that we can move the field from SpriteItem to SlotItem, but for now this commit makes the project's items have two different name variables.

The equality and hash functions are fine, they just have to be changed and moved.
For SlotItem define an abstract equality and hash functions.
For SpriteItem use the existing functions for the name (if types are equal).

2024-10-13 03:11 UTC, Aleksei-Spiridonov commented on Assets/GameplayObjects/Screwdriver/InteractableScrewdriver.cs
That's what I ment. Here we set this second name with code despite having it as an ScriptableObject property.
The screwdiver does have a name as a SpriteItem.name

2024-10-13 03:11 UTC, KOMPOT-IZ-FIKUSA commented on Assets/Scripts/InteractableVent.cs
I see the pattern:
1) Find the screwdriver in the world
2) Get an item from the screwdriver
3) Compare items with selected item

Problems here:
1) The existance of the screwdiver in the scene is assumed
2) Two compared items are actually different items:
The screwdriver in the player'r inventory is a different object than the screwdriver that the object returns. They are copies of the same screwdriver ScriptableObject, but they are different objects.
3) Getting an item and using a defined comparison can be simplified by just cheking its name.
If we need any complex logic, we can bind the screwriver SpriteItem as a [SerializeField] to the script avoiding finding it in the scene

Overall, make a simple string comparison (get name from SpriteItem of selected) without doing two operations with objects.
You can even make a function 
private static bool IsScrewdriver(SlotItem item) {return item is SpriteItem && (item as SpriteItem).name.Lower() == "screwdriver";}

2024-10-13 03:11 UTC, KOMPOT-IZ-FIKUSA commented on ProjectSettings/TagManager.asset
No need but ok 
: )

2024-10-13 03:25 UTC, KOMPOT-IZ-FIKUSA reviewed
Rename the function (or maybe you did in future commits) and make it clear about the invoke

2024-10-13 03:25 UTC, KOMPOT-IZ-FIKUSA commented on Assets/CoreSystems/InteractionUI/InteractionUIController.cs
Not clear what is HintMessage.
It should be either renamed to ClearHintMessage or marked as TODO: ... if it is undone

2024-10-13 03:25 UTC, KOMPOT-IZ-FIKUSA commented on Assets/Scripts/InteractableVent.cs
1) string for ventHint ok
2) (still ok, no actual problems caused by this) No need to use public search in order to get InteractionUIController since it is accessible via
InteractableObject,playerController.interactionUIController (add a public getter there)
3) What InteractionUIController.Invoke does??

2024-10-13 03:26 UTC, KOMPOT-IZ-FIKUSA approved these changes
Some changes in the scene that I believe don't kill the project.
Some added empty lines in the code.
Approved.

2024-10-13 03:26 UTC, KOMPOT-IZ-FIKUSA approved these changes
ok

2024-10-15 18:23 UTC, merged

2024-10-16 17:13 UTC, Chpcunningham commented on Assets/Scripts/InteractableVent.cs
I believe I fixed this already!

2024-10-16 17:14 UTC, Chpcunningham commented on Assets/CoreSystems/Storage/Scripts/BaseStorageSystem/SlotItem.cs
Used a string comparison! WORKED!

2024-10-16 17:16 UTC, Chpcunningham commented on Assets/Scripts/InteractableVent.cs
DONE

2024-10-16 17:19 UTC, Chpcunningham commented on Assets/CoreSystems/InteractionUI/InteractionUIController.cs
Changed to ClearHintMessage